### PR TITLE
feat: support code block as component props

### PR DESCRIPTION
**Pull request by ManUtopiK**
This PR attempt to fix this issue https://github.com/nuxt/content/issues/1260

The goal is to write props components like a code block for **better readability** with a markdown formatter that don't know MDC syntax :
```
::home-hero
\```yaml
primary:
  text: 38K+ GitHub stars
  url: https://github.com/nuxt/nuxt.js
\```
::
```
(remove the `\`, it's break gfm).  

I added this feature with `experimental.componentCodeBlockProps` MDC options.

### CODE REVIEW

**Comment by ManUtopiK** [comment]
Possible regression with https://docus.dev/api/components#codegroup

**Comment by ManUtopiK** [comment]
Any feedback about this feature ?

**Comment by farnabaz** [comment]
Thank you for the pull-request.
This is feature is not planned yet, I'll put this PR at pending status. To discuss it later in next version's RFC

**Comment by ManUtopiK** [comment]
> Possible regression with https://docus.dev/api/components#codegroup
> 
> **edit:** I confirm, it breaks this component behaviour. A possible workaround is to use code block as props only with ```yaml and not ```yaml [title]

I've just fixed this behavior. Now only ```yaml can be used, so components like CodeGroup are not impacted by this feature.

A possible alternative is to use something like ```yaml [props] or ```yaml [content].
It will be nice to discuss this feature. I still have customers who complain that it breaks their markdown editor.
ping @Atinux

**Comment by Atinux** [comment]
I believe that this could be OK:

```
::home-hero
\```yaml[props]
primary:
  text: 38K+ GitHub stars
  url: https://github.com/nuxt/nuxt.js
\```
::
```

**Comment by Atinux** [comment]
```yaml [props] sound good too yes

**Comment by ManUtopiK** [comment]
Done.
I renamed this experimental feature `componentCodeBlockYamlProps`.
A little bit longer but more concise.

**Review by farnabaz — APPROVED** [review]

**Pull request merged**
